Repository icatproject/icat.server, pull requests merged in 2019-02, with the labels that each got.

#217 Fix integration test setup
  pom.xml
  src/test/install/.gitignore
  src/test/scripts/prepare_test.py
Labels: in progress, review wanted

#218 Update .travis.yml
  .travis.yml
Labels: in progress

#207 Implement the small schema additions
  pom.xml
  src/main/java/org/icatproject/core/entity/Instrument.java
  src/main/java/org/icatproject/core/entity/ParameterType.java
  src/main/java/org/icatproject/core/entity/Sample.java
  src/main/java/org/icatproject/core/entity/Shift.java
  src/main/java/org/icatproject/core/entity/Study.java
  src/main/java/org/icatproject/core/entity/User.java
  src/main/scripts/upgrade_mysql_4_10.sql
  src/main/scripts/upgrade_oracle_4_10.sql
  src/site/xhtml/installation.xhtml.vm
  src/site/xhtml/release-notes.xhtml
  src/test/java/org/icatproject/core/manager/TestEntityInfo.java
  src/test/java/org/icatproject/integration/TestRS.java
  src/test/java/org/icatproject/integration/TestWS.java
  src/test/java/org/icatproject/integration/WSession.java
  src/test/resources/icat.port
Labels: enhancement, review wanted
